services:
  backend:
    image: jmilcab353/backend:latest
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  frontend:
    image: jmilcab353/frontend:latest
    ports:
      - "80:80"

  db:
    image: jmilcab353/db:latest
    # image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    # volumes:
    #   - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql